=== daniluco16/Practica-Control-de-Versiones/xschema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
  <xs:element name="Instrumentos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="clasificacion">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="tipo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombretipo" type="xs:string" />
                    <xs:element name="definiciÃ³n" type="xs:string" />
                    <xs:element maxOccurs="unbounded" name="formaoejem">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="idtipo" type="xs:string" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="instrumento">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombreinstrumento" type="xs:string" />
              <xs:element name="urlinstrumento" type="xs:string" />
              <xs:element name="historia" type="xs:string" />
              <xs:element name="otrosinstrumentos" type="xs:string" />
              <xs:element name="interpretes">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="interprete">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nombre" type="xs:string" />
                          <xs:element name="apellidos" type="xs:string" />
                          <xs:element name="pais" type="xs:string" />
                          <xs:element name="url" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
            <xs:attribute name="idtipo" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== daniluco16/Practica-Control-de-Versiones/Actualizacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Instrumentos[
	<!ELEMENT Instrumentos (clasificacion,instrumento+)>
	<!ELEMENT clasificacion (tipo+)>
	<!ELEMENT tipo (nombretipo,definicion,formaoejem+)>
	<!ATTLIST tipo id ID #REQUIRED>
	<!ELEMENT nombretipo (#PCDATA)>
	<!ELEMENT definicion (#PCDATA)>
	<!ELEMENT formaoejem (#PCDATA)>
	<!ATTLIST formaoejem idtipo ID #REQUIRED>
	<!ELEMENT instrumento (nombreinstrumento,urlinstrumento,historia,otrosinstrumentos,interpretes)>
	<!ATTLIST instrumento id IDREF #REQUIRED>
	<!ATTLIST instrumento idtipo IDREF #REQUIRED>
	<!ELEMENT nombreinstrumento (#PCDATA)>
	<!ELEMENT urlinstrumento (#PCDATA)>
	<!ELEMENT historia (#PCDATA)>
	<!ELEMENT otrosinstrumentos (#PCDATA)>
	<!ELEMENT interpretes (interprete+)>
	<!ELEMENT interprete (nombre,apellidos,pais,url)>
     <!ELEMENT nombre (#PCDATA)>
	<!ELEMENT apellidos (#PCDATA)>
	<!ELEMENT pais (#PCDATA)>
	<!ELEMENT url (#PCDATA)>
]>
<!--<Instrumentos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xschema.xsd">-->
<Instrumentos>    
	<clasificacion>
        <tipo id="aire">
            <nombretipo>Aerófonos</nombretipo>
            <definicion>El sonido se produce al hacer vibrar una columna de aire</definicion>
            <formaoejem idtipo="boc">Boquilla o empuñadura</formaoejem>
            <formaoejem idtipo="bis">Bisel</formaoejem>
            <formaoejem idtipo="len_S">Lengüeta Simple</formaoejem>
            <formaoejem idtipo="len_D">Lengüeta doble</formaoejem>
            <formaoejem idtipo="len_L">Lengüeta libre</formaoejem>
            <formaoejem idtipo="Mix">Mixta</formaoejem>
        </tipo>
        <tipo id="cuerda">
            <nombretipo>Cordófonos</nombretipo>    
            <definicion>El sonido se produce al vibrar una cuerda tensa</definicion>
            <formaoejem idtipo="frotd">Frotada</formaoejem>
            <formaoejem idtipo="PVP">Pulsada o Pellizcada</formaoejem>
            <formaoejem idtipo="Perk">Percutida con teclado</formaoejem>
			
        </tipo>    
        <tipo id="idea">
            <nombretipo>Idiófonos</nombretipo>
            <definicion>El sonido se produce al vibrar el propio cuerpo del instrumento</definicion>
            <formaoejem idtipo="choque">Entrechoque</formaoejem>
            <formaoejem idtipo="GP">Golpeados o Percutidos</formaoejem>
            <formaoejem idtipo="Sacu">Sacudidos</formaoejem>
            <formaoejem idtipo="Rasp">Raspados</formaoejem>
            <formaoejem idtipo="Point">Punteados</formaoejem>
            <formaoejem idtipo="Frost">Frotados</formaoejem>
            <formaoejem idtipo="Sopl">Soplados</formaoejem>
        </tipo>    
        <tipo id="membrillo">    
            <nombretipo>Membranófonos</nombretipo>    
            <definicion>El sonido se produce al vibrar una membrana</definicion>
            <formaoejem idtipo="Pec">Percutidos</formaoejem>
            <formaoejem idtipo="Frost2">Frotados</formaoejem>
            <formaoejem idtipo="Sopl2">Soplados</formaoejem>
        </tipo>
        <tipo id="electric">
            <nombretipo>Electrófonos</nombretipo>
            <definicion>El sonido se produce por medios eléctricos</definicion>
            <formaoejem idtipo="Trad">Instrumentos tradicionales</formaoejem>
            <formaoejem idtipo="New">Nueva Construcción</formaoejem>  
        </tipo>    
    </clasificacion>        
<!--1-->              
    <instrumento id="aire" idtipo="boc">
        <nombreinstrumento>Tuba</nombreinstrumento>
        <urlinstrumento>http://www.el-atril.com/orquesta/Instrumentos/imagenes/tuba.jpg</urlinstrumento>
        <historia>La tuba es el mayor de los instrumentos de viento-metal y sus antecesores son el serpentón y el oficleido. Es uno de los instrumentos más recientemente añadidos a la orquesta sinfónica moderna, aparecido en 1835 con Wilhelm Friedrich Wieprecht y Johann Gottfried Moritz, sustituyendo al oficleido del siglo XVIII.</historia>
        <otrosinstrumentos>trompeta</otrosinstrumentos>
        <interpretes>
            <interprete>
                <nombre>Wilhelm</nombre>
                <apellidos>Friedrich Wieprecht</apellidos>
	            <pais>Alemania</pais>
	           <url>http://www.mz-web.de/image/view/2008/5/5/18416314,15753879,dmData,Wilhelm+Wieprecht+%25281212676436636%2529.jpg</url>
            </interprete>
            <interprete>
	           <nombre>Johann</nombre>
               <apellidos>Gottfried Moritz</apellidos>
	           <pais>Alemania</pais>
	           <url>http://e-ducation.datapeak.net/philosophers/herder.jpg</url>
            </interprete>
        </interpretes>    
    </instrumento>


<!--2-->
    <instrumento id="aire" idtipo="boc">
        <nombreinstrumento>trompa</nombreinstrumento>
        <urlinstrumento>https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/French_horn_front.png/200px-French_horn_front.png</urlinstrumento>
        <historia>Las trompas antiguas eran más sencillas que las actuales. Estas trompas antiguas eran hechas de tubos de metal y tenían una abertura "estallada" (pabellón o campana). Eran originalmente usadas en la cacería, a menudo montando a caballo. El cambio de tono era efectuado enteramente por los labios. Hasta el siglo XIX no iban equipadas con válvulas.</historia>
        <otrosinstrumentos>Bombardino</otrosinstrumentos>
        <interpretes>
            <interprete>
	           <nombre>Dennis</nombre>
               <apellidos>Brain</apellidos>
	           <pais>Inglaterra</pais>
	           <url>https://s3-us-west-2.amazonaws.com/find-a-grave-prod/photos/2011/243/9404_131488512944.jpg</url>
            </interprete>
            <interprete>
	           <nombre> Herbert von Karajan</nombre>
               <apellidos>Von Karajan</apellidos>    
	           <pais>Austria</pais>
	           <url>https://upload.wikimedia.org/wikipedia/commons/4/40/Bundesarchiv_Bild_183-S47421%2C_Herbert_von_Karajan.jpg</url>
            </interprete>
        </interpretes>
    </instrumento>

<!--3-->
   <instrumento id="aire" idtipo="boc">
        <nombreinstrumento>Trompeta</nombreinstrumento>
        <urlinstrumento>https://upload.wikimedia.org/wikipedia/commons/9/9d/Trumpet_1.jpg</urlinstrumento>
        <historia>La historia de la trompeta se remonta a los orígenes de la historia de la humanidad. Casi tan antiguas como la flauta, que se repunta como el instrumento más antiguo y generalizado, debieron ser la trompeta y la corneta, derivadas del cuerno de buey que aún puede servir como trompa de caza. Por tanto, las primeras trompetas fueron fabricadas con cuernos de animales cocidos, cañas de bambú, tubos vegetales ahuecados o conchas de moluscos y eran empleadas por los hombres primitivos para diversas cuestiones como eran los entierros, rituales para ahuyentar a los malos espíritus, para la caza o transmitir señales.</historia>
        <otrosinstrumentos>fliscorno</otrosinstrumentos>
        <interpretes>
            <interprete>
	           <nombre>Miles</nombre>
               <apellidos>Davis</apellidos>
	           <pais>Estados Unidos</pais>
	           <url>https://upload.wikimedia.org/wikipedia/commons/f/fa/Miles_Davis_by_Palumbo.jpg</url>
            </interprete>
            <interprete>
	           <nombre>John</nombre>
               <apellidos>Birks Gillespie</apellidos>
	           <pais>Estados Unidos</pais>
	           <url>https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Dizzy_Gillespie01.JPG/1024px-Dizzy_Gillespie01.JPG</url>
            </interprete>
       </interpretes>    
    </instrumento>

<!--4-->
    <instrumento id="aire" idtipo="boc">
        <nombreinstrumento>Trombón</nombreinstrumento>
        <urlinstrumento>https://upload.wikimedia.org/wikipedia/commons/1/11/Posaune.gif</urlinstrumento>
        <historia>La mayoría de la música compuesta para trombón se ha producido entre 1940 (fecha en que se escribió la Balada de Martin) y nuestros días. Se podría afirmar que el renacimiento del trombón comenzó en los Estados Unidos a comienzos del siglo XX. El trombonista de jazz Jack Teagarden y el súper-virtuoso Arthur Pryor, cada uno en su tipo de música, llevaron el trombón a unos límites antes no conseguidos.</historia>
        <otrosinstrumentos>Sacabuche</otrosinstrumentos>
        <interpretes>
            <interprete>
	           <nombre>Eddie</nombre>
               <apellidos>Bert</apellidos>
	           <pais>Estados Unidos</pais>
	           <url>https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Eddie_Bert.jpg/220px-Eddie_Bert.jpg</url>
            </interprete>
            <interprete>
	           <nombre>John A.</nombre>
               <apellidos>Jaki Byard</apellidos>
	           <pais>Estados Unidos</pais>
	           <url>http://www.jazzhistorydatabase.com/files/scans/byard/fs/Jaki%20Barney.jpg</url>
            </interprete>
        </interpretes>    
    </instrumento>

<!--5-->
    <instrumento id="aire" idtipo="boc">
        <nombreinstrumento>Helicón</nombreinstrumento>
        <urlinstrumento>https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Helikon-Stowasser-Graz.jpg/800px-Helikon-Stowasser-Graz.jpg</urlinstrumento>
        <historia>Este instrumento es muy popular en Europa central y oriental y es una opción para fanfarrias militares. Su tesitura se sitúa dos octavas por debajo de la de un corneta</historia>
        <otrosinstrumentos >Sousafón</otrosinstrumentos>
        <interpretes>
            <interprete>
	           <nombre>Guardia</nombre>
               <apellidos>Republicana de Francia</apellidos>    
               <pais>Francia</pais>
	           <url>https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/French_Republican_Guard_cavalry_fanfare_DSC03125.JPG/1024px-French_Republican_Guard_cavalry_fanfare_DSC03125.JPG</url>
            </interprete>
            <interprete>
	           <nombre>Guardia</nombre>
               <apellidos>Republicana de Francia</apellidos>
	           <pais>Francia</pais>
